#!/bin/bash
# M-ALMIS Security Hardening & Resource Optimization
# Fixes: SSH security, Ollama memory, process cleanup, temp cleanup

G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; C='\033[0;36m'; NC='\033[0m'
echo ""
echo -e "${C}M-ALMIS Security Hardening & Optimization${NC}"
echo ""

# ═══ 1. SSH HARDENING ═══
echo -e "${C}── 1. SSH Security ──${NC}"
if [ -f /etc/ssh/sshd_config ]; then
    # Backup
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak 2>/dev/null
    
    # Disable root password login
    sed -i 's/^PermitRootLogin yes/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config 2>/dev/null
    sed -i 's/^#PermitRootLogin yes/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config 2>/dev/null
    
    # Disable password auth (use key-only)
    sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config 2>/dev/null
    sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config 2>/dev/null
    
    echo -e "  ${G}✓${NC} SSH: Root login restricted to key-only"
    echo -e "  ${G}✓${NC} SSH: Password authentication disabled"
    echo -e "  ${Y}⚠${NC} SSH: Restart sshd to apply (service ssh restart)"
else
    echo -e "  ${Y}⚠${NC} SSH config not found"
fi

# ═══ 2. OLLAMA MEMORY OPTIMIZATION ═══
echo ""
echo -e "${C}── 2. Ollama Memory Optimization ──${NC}"

# Kill existing ollama
pkill -f "ollama serve" 2>/dev/null
sleep 2

# Create optimized Ollama config
mkdir -p /root/.ollama
cat > /root/.ollama/config.json << 'OLLAMA_CFG'
{
  "llm": {
    "num_threads": 4,
    "num_ctx": 2048,
    "num_batch": 256,
    "num_gpu": 0
  },
  "keep_alive": "5m",
  "max_loaded_models": 1
}
OLLAMA_CFG

echo -e "  ${G}✓${NC} Ollama config: threads=4, context=2048, batch=256"
echo -e "  ${G}✓${NC} Ollama config: max_loaded_models=1 (saves RAM)"

# Restart ollama with optimized settings
OLLAMA_NUM_THREADS=4 OLLAMA_MAX_LOADED_MODELS=1 setsid /usr/local/bin/ollama serve > /dev/null 2>&1 &
sleep 3
if curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
    echo -e "  ${G}✓${NC} Ollama restarted with optimized settings"
else
    echo -e "  ${Y}⚠${NC} Ollama restart pending..."
fi

# ═══ 3. TEMP FILE CLEANUP ═══
echo ""
echo -e "${C}── 3. Temp File Cleanup ──${NC}"

# Clean old uploads
UPLOADS="/tmp/codex-web-uploads"
if [ -d "$UPLOADS" ]; then
    BEFORE=$(du -sh "$UPLOADS" 2>/dev/null | awk '{print $1}')
    find "$UPLOADS" -name "*.txt" -mtime +1 -delete 2>/dev/null
    find "$UPLOADS" -type d -empty -delete 2>/dev/null
    AFTER=$(du -sh "$UPLOADS" 2>/dev/null | awk '{print $1}')
    echo -e "  ${G}✓${NC} Cleaned temp uploads: ${BEFORE} → ${AFTER}"
fi

# Clean old logs
LOG_DIR="/root/Documents/Codex/2026-07-11/if-you-need-to-run-this"
for f in "$LOG_DIR"/*.log; do
    if [ -f "$f" ]; then
        SIZE=$(stat -c%s "$f" 2>/dev/null || echo 0)
        if [ "$SIZE" -gt 1048576 ]; then  # >1MB
            # Keep last 1000 lines
            tail -1000 "$f" > "${f}.tmp" && mv "${f}.tmp" "$f"
            echo -e "  ${G}✓${NC} Trimmed $(basename $f): $(du -h "$f" | awk '{print $1}')"
        fi
    fi
done

# Clean old python cache
find /root/Documents/Codex/2026-07-11/if-you-need-to-run-this/ -name "__pycache__" -exec rm -rf {} + 2>/dev/null
echo -e "  ${G}✓${NC} Cleaned Python cache"

# ═══ 4. PROCESS OPTIMIZATION ═══
echo ""
echo -e "${C}── 4. Process Optimization ──${NC}"

# Kill zombie/stale processes
STALE=$(ps aux 2>/dev/null | awk '$8 ~ /Z/ {print $2}' | wc -l)
if [ "$STALE" -gt 0 ]; then
    ps aux 2>/dev/null | awk '$8 ~ /Z/ {print $2}' | xargs kill -9 2>/dev/null
    echo -e "  ${G}✓${NC} Killed ${STALE} zombie processes"
else
    echo -e "  ${G}✓${NC} No zombie processes"
fi

# Clean old head/sort pipes
pkill -f "^head$" 2>/dev/null
pkill -f "^sort$" 2>/dev/null
echo -e "  ${G}✓${NC} Cleaned stale pipe processes"

# ═══ 5. SECURITY AUDIT ═══
echo ""
echo -e "${C}── 5. Security Audit ──${NC}"

# Check .env permissions
ENV="/root/Documents/Codex/2026-07-11/if-you-need-to-run-this/.env"
if [ -f "$ENV" ]; then
    PERMS=$(stat -c%a "$ENV" 2>/dev/null)
    if [ "$PERMS" != "600" ]; then
        chmod 600 "$ENV"
        echo -e "  ${G}✓${NC} Fixed .env permissions: ${PERMS} → 600"
    else
        echo -e "  ${G}✓${NC} .env permissions OK (600)"
    fi
fi

# Check for exposed secrets in logs
for f in "$LOG_DIR"/*.log; do
    if grep -qiE "token|password|secret" "$f" 2>/dev/null; then
        echo -e "  ${Y}⚠${NC} $(basename $f) may contain secrets — review needed"
    fi
done

# Create security config
cat > "$LOG_DIR/security.conf" << 'SEC'
# AD-SMTA Security Configuration
# Generated by hardening script

# SSH Security
SSH_PERMIT_ROOT=prohibit-password
SSH_PASSWORD_AUTH=no

# Ollama Security
OLLAMA_HOST=127.0.0.1:11434
OLLAMA_MAX_LOADED_MODELS=1
OLLAMA_NUM_THREADS=4

# API Security
DERIV_TOKEN_LOCATION=.env
ENV_PERMISSIONS=600

# Process Limits
MAX_OLLAMA_THREADS=4
MAX_CONTEXT_SIZE=2048
MAX_BATCH_SIZE=256

# Resource Limits
MAX_RAM_MB=6000
MAX_CPU_LOAD=4.0
MAX_TEMP_CELSIUS=42
SEC

echo -e "  ${G}✓${NC} Created security.conf"

# ═══ 6. RESOURCE MONITOR ═══
echo ""
echo -e "${C}── 6. Resource Monitor ──${NC}"

cat > "$LOG_DIR/resource_monitor.sh" << 'MONITOR'
#!/bin/bash
# Continuous resource monitor for M-ALMIS
# Runs every 60 seconds, logs warnings

LOG="/root/Documents/Codex/2026-07-11/if-you-need-to-run-this/resource.log"

while true; do
    MEM_PCT=$(free -m 2>/dev/null | awk '/Mem:/{printf "%.0f", $3*100/$2}')
    LOAD=$(cat /proc/loadavg 2>/dev/null | awk '{print $1}')
    TEMP=$(termux-battery-status 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['temperature'])" 2>/dev/null || echo "0")
    
    TS=$(date '+%H:%M:%S')
    
    # Log if resources are high
    if [ "${MEM_PCT:-0}" -gt 80 ]; then
        echo "[$TS] HIGH_MEM: ${MEM_PCT}%" >> "$LOG"
    fi
    if [ "$(echo "$LOAD > 4.0" | bc 2>/dev/null)" = "1" ]; then
        echo "[$TS] HIGH_LOAD: $LOAD" >> "$LOG"
    fi
    TEMP_INT=$(echo "$TEMP" | cut -d. -f1)
    if [ "${TEMP_INT:-0}" -gt 40 ]; then
        echo "[$TS] HIGH_TEMP: ${TEMP}°C" >> "$LOG"
    fi
    
    sleep 60
done
MONITOR

chmod +x "$LOG_DIR/resource_monitor.sh"
echo -e "  ${G}✓${NC} Created resource_monitor.sh"

# ═══ 7. GOVERNANCE CONFIG ═══
echo ""
echo -e "${C}── 7. Governance Configuration ──${NC}"

cat > "$LOG_DIR/governance.conf" << 'GOV'
# M-ALMIS Governance Rules
# Resource-aware mobile intelligence system

# Resource Modes
MODE_LIGHT_TEMP_THRESHOLD=42
MODE_LIGHT_BATTERY_THRESHOLD=20
MODE_LIGHT_RAM_THRESHOLD=85
MODE_NORMAL_RAM_THRESHOLD=70
MODE_RESEARCH_RAM_THRESHOLD=50

# Agent Limits
MAX_CONCURRENT_AGENTS=3
MAX_SIMULATION_TRADES=100
MAX_SIMULATION_RUNS=500
MIN_TRADES_FOR_APPROVAL=10

# Risk Governance
MAX_DAILY_LOSS_PCT=2
MAX_STAKE_PCT=10
MAX_CONCURRENT_TRADES=1
MIN_EDGE_PCT=1
KELLY_FRACTION=10

# Memory Governance
MAX_TRADE_HISTORY=500
MAX_STRATEGY_HISTORY=100
MEMORY_COMPRESS_INTERVAL=100
MEMORY_RETENTION_DAYS=30

# Security Governance
ENV_PERMISSIONS=600
SSH_KEY_ONLY=true
OLLAMA_LOCALHOST_ONLY=true
API_KEY_ROTATION_DAYS=30

# Self-Improvement Rules
EVOLUTION_CHECK_INTERVAL=20
MIN_EVOLUTION_TRADES=5
PERFORMANCE_DECLINE_THRESHOLD=15
GOV

echo -e "  ${G}✓${NC} Created governance.conf"

# ═══ SUMMARY ═══
echo ""
echo -e "${C}═══════════════════════════════════════════════${NC}"
echo -e "  ${G}Hardening Complete${NC}"
echo ""
echo -e "  Files created:"
echo -e "    ${G}✓${NC} security.conf — Security settings"
echo -e "    ${G}✓${NC} governance.conf — Resource & risk rules"
echo -e "    ${G}✓${NC} resource_monitor.sh — Continuous monitoring"
echo -e "    ${G}✓${NC} /root/.ollama/config.json — Optimized Ollama"
echo ""
echo -e "  Changes applied:"
echo -e "    ${G}✓${NC} SSH hardened (key-only, no root password)"
echo -e "    ${G}✓${NC} Ollama optimized (4 threads, 2K context)"
echo -e "    ${G}✓${NC} Temp files cleaned"
echo -e "    ${G}✓${NC} Python cache cleaned"
echo -e "    ${G}✓${NC} .env permissions fixed"
echo -e "    ${G}✓${NC} Zombie processes killed"
echo ""
echo -e "${C}═══════════════════════════════════════════════${NC}"
